version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: tarot-reader-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # Development mode with hot reload
  api-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: tarot-reader-api-dev
    ports:
      - "8001:8000"
    volumes:
      - ./src:/app/src:ro
      - ./api:/app/api:ro
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    profiles:
      - dev
